# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\views\pricing\pricingboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1026, 503)
        self.pricingBoard = QtWidgets.QTableWidget(Form)
        self.pricingBoard.setGeometry(QtCore.QRect(20, 50, 751, 411))
        self.pricingBoard.setObjectName("pricingBoard")
        self.pricingBoard.setColumnCount(8)
        self.pricingBoard.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.pricingBoard.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pricingBoard.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pricingBoard.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pricingBoard.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pricingBoard.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pricingBoard.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.pricingBoard.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.pricingBoard.setHorizontalHeaderItem(7, item)
        self.updateTime = QtWidgets.QLabel(Form)
        self.updateTime.setGeometry(QtCore.QRect(90, 470, 181, 16))
        self.updateTime.setObjectName("updateTime")
        self.refreshButton = QtWidgets.QPushButton(Form)
        self.refreshButton.setGeometry(QtCore.QRect(900, 30, 75, 51))
        self.refreshButton.setObjectName("refreshButton")
        self.openUrlButton = QtWidgets.QPushButton(Form)
        self.openUrlButton.setGeometry(QtCore.QRect(900, 110, 75, 24))
        self.openUrlButton.setObjectName("openUrlButton")
        self.editButton = QtWidgets.QPushButton(Form)
        self.editButton.setGeometry(QtCore.QRect(800, 30, 75, 51))
        self.editButton.setObjectName("editButton")
        self.detailBrowser = QtWidgets.QTextBrowser(Form)
        self.detailBrowser.setGeometry(QtCore.QRect(800, 160, 181, 301))
        self.detailBrowser.setObjectName("detailBrowser")
        self.startButton = QtWidgets.QPushButton(Form)
        self.startButton.setGeometry(QtCore.QRect(800, 110, 75, 24))
        self.startButton.setObjectName("startButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(21, 470, 64, 16))
        self.label.setObjectName("label")
        self.productName = QtWidgets.QLabel(Form)
        self.productName.setGeometry(QtCore.QRect(20, 20, 741, 16))
        self.productName.setObjectName("productName")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.pricingBoard.horizontalHeaderItem(0)
        item.setText(_translate("Form", "No.1"))
        item = self.pricingBoard.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Rank"))
        item = self.pricingBoard.horizontalHeaderItem(2)
        item.setText(_translate("Form", "U.Price"))
        item = self.pricingBoard.horizontalHeaderItem(3)
        item.setText(_translate("Form", "L.Price"))
        item = self.pricingBoard.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Reduce"))
        item = self.pricingBoard.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Profit"))
        item = self.pricingBoard.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Status"))
        item = self.pricingBoard.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Name"))
        self.updateTime.setText(_translate("Form", "Oct.01.1990 12:00:00"))
        self.refreshButton.setText(_translate("Form", "Refresh"))
        self.openUrlButton.setText(_translate("Form", "Open"))
        self.editButton.setText(_translate("Form", "Edit"))
        self.startButton.setText(_translate("Form", "Start"))
        self.label.setText(_translate("Form", "Updated at: "))
        self.productName.setText(_translate("Form", "Product"))
