from views.pricing.mainpricingboard import MainPricingBoard
from views.pricing.components.configurepricing import ConfigurePricingLogic
from views.pricing.components.competitorstat import CompetitorStatLogic, CompetitorStatDialog
from views.mainwindow import MainWindow