# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\views\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 22))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuPricing = QtWidgets.QMenu(self.menuEdit)
        self.menuPricing.setObjectName("menuPricing")
        self.menuEmail = QtWidgets.QMenu(self.menuEdit)
        self.menuEmail.setObjectName("menuEmail")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionBulk = QtWidgets.QAction(MainWindow)
        self.actionBulk.setObjectName("actionBulk")
        self.actionlogin = QtWidgets.QAction(MainWindow)
        self.actionlogin.setObjectName("actionlogin")
        self.menuPricing.addAction(self.actionSettings)
        self.menuEmail.addAction(self.actionBulk)
        self.menuEdit.addAction(self.menuPricing.menuAction())
        self.menuEdit.addAction(self.menuEmail.menuAction())
        self.menuEdit.addAction(self.actionlogin)
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuEdit.setTitle(_translate("MainWindow", "Window"))
        self.menuPricing.setTitle(_translate("MainWindow", "Pricing"))
        self.menuEmail.setTitle(_translate("MainWindow", "Email"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionBulk.setText(_translate("MainWindow", "Bulk"))
        self.actionlogin.setText(_translate("MainWindow", "login"))
