# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configurepricing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(702, 640)
        self.confirmBox = QtWidgets.QDialogButtonBox(Dialog)
        self.confirmBox.setGeometry(QtCore.QRect(530, 20, 81, 91))
        self.confirmBox.setOrientation(QtCore.Qt.Vertical)
        self.confirmBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirmBox.setObjectName("confirmBox")
        self.configureTable = QtWidgets.QTableWidget(Dialog)
        self.configureTable.setGeometry(QtCore.QRect(15, 20, 501, 591))
        self.configureTable.setObjectName("configureTable")
        self.configureTable.setColumnCount(4)
        self.configureTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.configureTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.configureTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.configureTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.configureTable.setHorizontalHeaderItem(3, item)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(530, 110, 151, 146))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.server = QtWidgets.QLineEdit(self.widget)
        self.server.setObjectName("server")
        self.verticalLayout.addWidget(self.server)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.shopName = QtWidgets.QLineEdit(self.widget)
        self.shopName.setObjectName("shopName")
        self.verticalLayout.addWidget(self.shopName)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pricingFreq = QtWidgets.QSpinBox(self.widget)
        self.pricingFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pricingFreq.setMinimum(1)
        self.pricingFreq.setMaximum(999999)
        self.pricingFreq.setObjectName("pricingFreq")
        self.verticalLayout.addWidget(self.pricingFreq)

        self.retranslateUi(Dialog)
        self.confirmBox.accepted.connect(Dialog.accept) # type: ignore
        self.confirmBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pricing Configuration"))
        item = self.configureTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "GTIN"))
        item = self.configureTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name"))
        item = self.configureTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Note"))
        item = self.configureTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "L.Price"))
        self.label_3.setText(_translate("Dialog", "Server URL"))
        self.label.setText(_translate("Dialog", "Shop Name"))
        self.label_2.setText(_translate("Dialog", "Pricing Freq."))
