# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'competitorstat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(652, 311)
        self.sellerBoard = QtWidgets.QTableWidget(Widget)
        self.sellerBoard.setGeometry(QtCore.QRect(20, 40, 611, 251))
        self.sellerBoard.setObjectName("sellerBoard")
        self.sellerBoard.setColumnCount(7)
        self.sellerBoard.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sellerBoard.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sellerBoard.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sellerBoard.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sellerBoard.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sellerBoard.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sellerBoard.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.sellerBoard.setHorizontalHeaderItem(6, item)
        self.productLabel = QtWidgets.QLabel(Widget)
        self.productLabel.setGeometry(QtCore.QRect(20, 10, 571, 16))
        self.productLabel.setObjectName("productLabel")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        item = self.sellerBoard.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "Seller"))
        item = self.sellerBoard.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "Label"))
        item = self.sellerBoard.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "U.Price"))
        item = self.sellerBoard.horizontalHeaderItem(3)
        item.setText(_translate("Widget", "T.Price"))
        item = self.sellerBoard.horizontalHeaderItem(4)
        item.setText(_translate("Widget", "Shipment 1"))
        item = self.sellerBoard.horizontalHeaderItem(5)
        item.setText(_translate("Widget", "Shipment 2"))
        item = self.sellerBoard.horizontalHeaderItem(6)
        item.setText(_translate("Widget", "Qty"))
        self.productLabel.setText(_translate("Widget", "productName"))
