# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newofferdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(495, 250)
        self.confirmBox = QtWidgets.QDialogButtonBox(Dialog)
        self.confirmBox.setGeometry(QtCore.QRect(20, 200, 241, 32))
        self.confirmBox.setOrientation(QtCore.Qt.Horizontal)
        self.confirmBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirmBox.setObjectName("confirmBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 91, 16))
        self.label_3.setObjectName("label_3")
        self.productName = QtWidgets.QLabel(Dialog)
        self.productName.setGeometry(QtCore.QRect(20, 20, 251, 41))
        self.productName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.productName.setWordWrap(True)
        self.productName.setIndent(-1)
        self.productName.setObjectName("productName")
        self.quantity = QtWidgets.QSpinBox(Dialog)
        self.quantity.setGeometry(QtCore.QRect(150, 110, 111, 22))
        self.quantity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.quantity.setMaximum(999999)
        self.quantity.setObjectName("quantity")
        self.unitPrice = QtWidgets.QDoubleSpinBox(Dialog)
        self.unitPrice.setGeometry(QtCore.QRect(150, 80, 111, 22))
        self.unitPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitPrice.setSingleStep(0.02)
        self.unitPrice.setObjectName("unitPrice")
        self.shippingGroup = QtWidgets.QComboBox(Dialog)
        self.shippingGroup.setGeometry(QtCore.QRect(150, 140, 111, 22))
        self.shippingGroup.setObjectName("shippingGroup")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(290, 80, 191, 141))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        self.confirmBox.accepted.connect(Dialog.accept) # type: ignore
        self.confirmBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Quantity"))
        self.label_2.setText(_translate("Dialog", "Unit Price"))
        self.label_3.setText(_translate("Dialog", "Shipping Group"))
        self.productName.setText(_translate("Dialog", "product"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">L.Price</span>:    {{lprice}}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Profit</span>:    {{profit}}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Total</span>:    {{total}}</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
